# Generated by Django 3.2.13 on 2022-07-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_no',
            new_name='phone',
        ),
    ]
